### ISSUE TITLE
Add tests for the repository module

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#186]
- [x] repository.get_revs (#380)
- [x] repository.get_directories (#381)
- [x] repository.download_commits (#379)
- [x] repository.calculate_experiences (#382)
- [x] repository.hg_log (#385)
- [ ] repository._transform (#384)
- [ ] repository.get_commits (#383)
- [x] repository.download_component_mapping (#535)

**Comment by ayush1999** [comment]
@marco-c Should I take this up? If so, what should these tests include?

**Comment by marco-c** [comment]
This is going to be a bit involved. You're going to have to create a test mercurial repository and generate a few commits in it in order to test all the functions in repository.py.

The first tests, testing the behavior of _transform, should not require a test repository though (you can create some fake commit objects), so you can start with those.

**Comment by marco-c** [comment]
> The first tests, testing the behavior of _transform, should not require a test repository though (you can create some fake commit objects), so you can start with those.

No, actually even for testing _transform you'll need a test repository.

**Comment by ayush1999** [comment]
Ok, correct me if I'm wrong, when the tests for repository start, it'll first clone the dummy repo into tests/data, and then test the repository function, right?

**Comment by marco-c** [comment]
The test itself will create the repository, it won't clone it.

**Comment by ayush1999** [comment]
Could you explain what you mean by the test creating the repository? I was thinking about hosting a dummy repo on bitbucket, and cloning it at the time of the test (I'm guessing there's an extension to clone hg repo from python?).

**Comment by marco-c** [comment]
Having the test repository outside of this repository will make it much harder to add new tests and modify the existing ones. Also, it will make it hard to perform bisection.

Instead, we can just create the repository locally as part of the test setup.

**Comment by ayush1999** [comment]
Sure, I'll add the repo to test/data. Also, off topic: how is https://github.com/mozilla/bugbug/blob/master/bugbug/repository.py#L122 supposed to be used? (I keep getting empty lists). The date parameter is the date from which all commits should be collected, I reckon? 

`hg.log(revrange='pushdate("{}")'.format(datetime.datetime(2019, 1, 1, 0,0,0).strftime('%Y-%m-%d')), limit=1)`gives me an empty list ,although there are commits after the date.

**Comment by marco-c** [comment]
> Sure, I'll add the repo to test/data

It's better if we create the repo programmatically with Python, using hglib. Having a whole repo inside the repo just for testing purposes would have a few problems too (not easily modifiable).

> Also, off topic: how is https://github.com/mozilla/bugbug/blob/master/bugbug/repository.py#L122 supposed to be used?

You'll need to enable these three mercurial extensions:
```
pushlog = /PATH/version-control-tools/hgext/pushlog
hgmo = /PATH/version-control-tools/hgext/hgmo
mozext = /PATH/version-control-tools/hgext/mozext
```

If you run `./mach boostrap` or `./mach vcs-setup` in your mozilla-central clone, /PATH will be YOUR_HOME_DIRECTORY/.mozbuild/

**Comment by marco-c** [comment]
> It's better if we create the repo programmatically with Python, using hglib. Having a whole repo inside the repo just for testing purposes would have a few problems too (not easily modifiable).

Here's a brief example from another project, you can take inspiration from it https://github.com/mozilla/release-services/blob/549691a0365854fe0c9e03c01728b7f66d7cbe9b/src/staticanalysis/bot/tests/conftest.py#L53.

**Comment by ayush1999** [comment]
Thanks, I'll dig into it. By the way, @marco-c how do you use hg with this project? hg4.8 uses python2.7, whereas this project uses python3. (I'm trying to fix the `hgmo : no module named utils` error I was getting earlier, to use the log function)

**Comment by ayush1999** [comment]
Nevermind, I figured it out.

**Comment by ayush1999** [comment]
@marco-c I've updated my hg to 4.9, and added all those extensions, however I still get an empty list:
```
>>> import bugbug
>>> from bugbug import repository
>>> import datetime
>>> import hglib
>>> hg = hglib.open("mozilla-central")
>>> hg.log(revrange='pushdate("{}")'.format(datetime.datetime(2019,1,1,1,1,1).strftime('%Y-%m-%d')), limit=1)
[]
```
Using only `hg.log()` gives the correct results. Any idea why this is happening?

**Comment by ayush1999** [comment]
> > It's better if we create the repo programmatically with Python, using hglib. Having a whole repo inside the repo just for testing purposes would have a few problems too (not easily modifiable).
> 
> Here's a brief example from another project, you can take inspiration from it https://github.com/mozilla/release-services/blob/549691a0365854fe0c9e03c01728b7f66d7cbe9b/src/staticanalysis/bot/tests/conftest.py#L53.

Also, can you please test if the `client.commit()` functions works for you? (I keep getting a `hglib.error.CommandError: (1, b'committing files:\ntest.cpp\ntest.txt\ncommitting manifest\ncommitting changelog\nupdating the branch cache\nnothing changed', b'')`). I'm on Python3.7 , hg 4.8.2.

**Comment by marco-c** [comment]
> Using only hg.log() gives the correct results. Any idea why this is happening?

Not sure, maybe your pushlog database is empty. It will probably be rebuilt if you go in the repo directory and run `hg pull central` and `hg up central`.

**Comment by marco-c** [comment]
> Also, can you please test if the client.commit() functions works for you?

Yes, the test I sent you works for me.

**Comment by ayush1999** [comment]
Yes, 

> > Using only hg.log() gives the correct results. Any idea why this is happening?
> 
> Not sure, maybe your pushlog database is empty. It will probably be rebuilt if you go in the repo directory and run `hg pull central` and `hg up central`.

Great, this got it running for me. Thanks :+1: 


> > Also, can you please test if the client.commit() functions works for you?
> 
> Yes, the test I sent you works for me.

It still doesn't work for me. It's probably because of version issues. Can you tell me what python and hg you're on?

**Comment by marco-c** [comment]
Python 3.7.2+ and Mercurial 4.8.

Can you show me exactly what code you're running?

**Comment by ayush1999** [comment]
Sure:
```
test_path = 'tests/fixtures/test_repository'
hglib.init(test_path)

client = hglib.open(test_path)

path = os.path.join(test_path, 'test.txt')
with open(path, 'w') as f:
    f.write('Hello World\n')
client.add(path.encode('utf-8'))

path = os.path.join(test_path, 'test.cpp')
with open(path, 'w') as f:
    f.write('Hello World\n')
client.add(path.encode('utf-8'))

client.commit(b'Hello World', user=b'Tester')
```
Error: 
```
hglib.error.CommandError: (1, b'committing files:\ntest.cpp\ntest.txt\ncommitting manifest\ncommitting changelog\nupdating the branch cache\nnothing changed', b'')

../bbug/lib/python3.7/site-packages/hglib/client.py:263: CommandError
```

Can you please tell me where I might be going wrong?

**Comment by marco-c** [comment]
Your script works for me. Have you tried running it as a script in isolation from tests?

When using it as a fixture, try using a temporary directory instead as test_path (using https://docs.pytest.org/en/latest/tmpdir.html).

**Comment by ayush1999** [comment]
@marco-c Yes, I tried that, the `commit()` function still results in an error. I'm on Python 3.7.1, hg 4.8.2. Is it possible this is because of some version errors? (If so, I'll try using the exact python version you're on.)

**Comment by marco-c** [comment]
It's very strange, I wouldn't expect this to be due to some version problem.

**Comment by ayush1999** [comment]
I remember this to be working on my earlier system. I changed my system couple of days back, and it's been failing ever since.

**Comment by ayush1999** [comment]
I think I'll leave this issue for someone else interested (until I figure out why this is happening.)

**Comment by marco-c** [comment]
Some initial tests are being added in #377.

**Comment by marco-c** [comment]
Closing this as each needed test has been filed as a separate issue.
