### ISSUE TITLE
Prepare for classification of `comments`

### ISSUE THREAD

**Issue by johnpangas** [mozilla/bugbug#4094]
There are some tasks that need to be done to prepare for `comment` models:
```[tasklist]
### Tasks
- [x] Create a function to  `get_comment` from Bugzilla using `comment_id`
- [x] Create a `comment_classifier` script that classifies using `comment_id`
- [x] Create a function in `http_service` to classify comments using a list of `comment_ids`
- [ ] Create a comment classification job.
- [ ] Create a function to classify a single or batch comments. (in `http_service/bugbug_http/app.py`)
```
This issue would also be a good place to discuss on the best way to run models on comments:
With the proposed task list above, it was considering to classify comments independently of bugs by using comment_ids.

I thought it would be wise to separate this work from #3994 to minimise the amount of reviews needed to land the model.

**Comment by jpangas** [comment]
WDYT @suhaibmujahid and @marco-c ?

**Comment by marco-c** [comment]
Sounds like a good plan to me. In the future, we might consider adding the bug ID too in case of a model which would classify a given comment based on the previous context.
