### ISSUE TITLE
Support classifying commits for test selection

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#632]
- [x] Add a setup step to the http service to setup the environment for classifying commits - #1299
- [x] Add the scaffolding needed to add an API call to select tests - #1300
- [x] In the API to select tests, apply the requested patch - #1301 and #1372
- [x] Download test scheduling models in the HTTP service - #1330
- [x] In the API to select tests, apply the model to select tests - #1302 

------------------------------------------------------------

This is not going to be so easy.
1. We need to clone a mercurial repository on the service
2. We need to download the commits DB from the commit_retrieval task
3. We need to update the commits DB whenever there are new commits on mozilla-central
4. The client will send a patch, we will apply the commit, analyze it to get its features, revert it

Similar to https://github.com/mozilla/relman-auto-nag/blob/b7bda7f4c29e59d36684b39fec522a79bacefcbb/auto_nag/scripts/regressor.py#L1, but this one is easier as it's only analyzing new real commits, we will instead analyze proposed patches too (which might or might not be landed at some point).

**Comment by marco-c** [comment]
For 1, we likely need batch checkout as pulselistener, as otherwise we can't clone mozilla-central on Heroku.

**Comment by marco-c** [comment]
I'm starting to write this as a script, which we can then move to an API endpoint.

**Comment by Lothiraldan** [comment]
Sounds good, the hardest part seems to be applying the patch locally as it involves the disk. Does `https://github.com/mozilla/bugbug/blob/master/bugbug/repository.py#L270` is retrieving all the information needed for the commits or other functions are retrieving other information?

**Comment by marco-c** [comment]
There are other functions too, all called from https://github.com/mozilla/bugbug/blob/89bba8efcaa418a8d2a0bfcfea4713e758e521ac/bugbug/repository.py#L662 (log, calculate_experiences, _transform). I should improve the names of these functions.

**Comment by Lothiraldan** [comment]
I take a look at what we are actually reading from the mercurial repository and I think that the data that requires to actually apply the patch is https://github.com/mozilla/bugbug/blob/master/bugbug/repository.py#L239.

I think we should be able to do all the work in-memory, maybe with a custom Mercurial extension so we don't need to fiddle with applying a patch then stripping it right after.

**Comment by marco-c** [comment]
I've added a script to the repo: https://github.com/mozilla/bugbug/commit/96ebe8777a333d08105fb39d83cee2cb052bae2c.
It is currently applying the patch and then reverting it, but we can try to avoid that (filed #664).

**Comment by marco-c** [comment]
There is now a hook https://tools.taskcluster.net/hooks/project-relman/bugbug-classify-patch which makes it easy to classify a Phabricator diff.
The downside of the hook vs a server is that we need to clone the Mercurial repository multiple times (whenever we trigger the hook) rather than just once (whenever we start the server). The upside is that it is very simple.

**Comment by Lothiraldan** [comment]
> I've added a script to the repo: [96ebe87](https://github.com/mozilla/bugbug/commit/96ebe8777a333d08105fb39d83cee2cb052bae2c).
> It is currently applying the patch and then reverting it, but we can try to avoid that (filed #664).

I don't see where the patch is reverted, did you send all of your commits?

I've answered on https://github.com/mozilla/bugbug/issues/664 for how we could avoid applying the patch on disk.

Do you want to starts using the hook in the HTTP service? I'm not sure if we can classify a single bug in a satisfying time, we are currently waiting only 100 seconds.

**Comment by marco-c** [comment]
> I don't see where the patch is reverted, did you send all of your commits?

When you run the script, the first step is cloning (https://github.com/mozilla/bugbug/blob/2997d222b00abe57ea8513a91044187c73f56cb1/bugbug/repository.py#L752) and cleaning (https://github.com/mozilla/bugbug/blob/2997d222b00abe57ea8513a91044187c73f56cb1/bugbug/repository.py#L733). So it is not reverted after beign applied, but on the second run of the script.

> Do you want to starts using the hook in the HTTP service? I'm not sure if we can classify a single bug in a satisfying time, we are currently waiting only 100 seconds.

We can probably avoid some of the steps that the script takes (e.g. we can pull periodically instead of for each classification).
Could you check what parts of the script take a long time? You can use 125397 as the diff_id.

**Comment by Lothiraldan** [comment]
> > I don't see where the patch is reverted, did you send all of your commits?
> 
> When you run the script, the first step is cloning (
> 
> https://github.com/mozilla/bugbug/blob/2997d222b00abe57ea8513a91044187c73f56cb1/bugbug/repository.py#L752
> ) and cleaning (
> 
> https://github.com/mozilla/bugbug/blob/2997d222b00abe57ea8513a91044187c73f56cb1/bugbug/repository.py#L733
> ). So it is not reverted after beign applied, but on the second run of the script.

Indeed the clone is stripping the outgoing commits which is a bit surprising.
> 
> > Do you want to starts using the hook in the HTTP service? I'm not sure if we can classify a single bug in a satisfying time, we are currently waiting only 100 seconds.
> 
> We can probably avoid some of the steps that the script takes (e.g. we can pull periodically instead of for each classification).
> Could you check what parts of the script take a long time? You can use 125397 as the diff_id.

I tried running the script locally already but I got an error, https://github.com/mozilla/bugbug/issues/671. I will time the working part so far.

**Comment by Lothiraldan** [comment]
Here are some of the slowest timings for the commit_classifier script:

- The initial clone took 27 minutes.
- Then the check + stripping takes ~13-15s.
- Downloading the data version takes ~3s.
- Downloading the data took ~32s.
- Iterating on all the commit takes ~19s.
- Applying the phab patch takes ~9-18s.
  - Where getting the patch from phabricator is around ~5-14s.
  - And importing it is around ~1-2s.
- Downloading the commits after the patch has been applied is ~21-24s.
- Classification is pretty quick actually ~3.5s.

Here are the raw timings:

```
Full clone
==========

Timer unit: 1e-06 s

Total time: 1710.61 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: update_commit_db at line 40

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    40                                               @profile
    41                                               def update_commit_db(self):
    42         1 1660847444.0 1660847444.0     97.1          repository.clone(self.repo_dir)
    43                                           
    44         1    1574629.0 1574629.0      0.1          db.download_version(repository.COMMITS_DB)
    45         1        617.0    617.0      0.0          if db.is_old_version(repository.COMMITS_DB) or not os.path.exists(
    46         1         11.0     11.0      0.0              repository.COMMITS_DB
    47                                                   ):
    48                                                       db.download(repository.COMMITS_DB, force=True, support_files_too=True)
    49                                           
    50    399171   16963656.0     42.5      1.0          for commit in repository.get_commits():
    51    399170     238914.0      0.6      0.0              pass
    52                                           
    53         1          3.0      3.0      0.0          rev_start = "children({})".format(commit["node"])
    54                                           
    55         1   30986175.0 30986175.0      1.8          repository.download_commits(self.repo_dir, rev_start)

Total time: 1711.03 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: classify at line 95

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    95                                               @profile
    96                                               def classify(self, diff_id):
    97         1 1711027980.0 1711027980.0    100.0          self.update_commit_db()

Clone ok, no data
=================

Timer unit: 1e-06 s

Total time: 213.921 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: update_commit_db at line 40

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    40                                               @profile
    41                                               def update_commit_db(self):
    42         1   14490475.0 14490475.0      6.8          repository.clone(self.repo_dir)
    43                                           
    44         1    3208754.0 3208754.0      1.5          db.download_version(repository.COMMITS_DB)
    45         1         72.0     72.0      0.0          if db.is_old_version(repository.COMMITS_DB) or not os.path.exists(
    46         1         15.0     15.0      0.0              repository.COMMITS_DB
    47                                                   ):
    48         1   32315039.0 32315039.0     15.1              db.download(repository.COMMITS_DB, force=True, support_files_too=True)
    49                                           
    50    400724   21069859.0     52.6      9.8          for commit in repository.get_commits():
    51    400723     339702.0      0.8      0.2              pass
    52                                           
    53         1          3.0      3.0      0.0          rev_start = "children({})".format(commit["node"])
    54                                           
    55         1  142496599.0 142496599.0     66.6          repository.download_commits(self.repo_dir, rev_start)

Total time: 18.6953 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: apply_phab at line 57

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    57                                               @profile
    58                                               def apply_phab(self, hg, diff_id):
    59         1          3.0      3.0      0.0          phabricator_api = PhabricatorAPI(
    60         1     758300.0 758300.0      4.1              api_key=get_secret("PHABRICATOR_TOKEN"), url=get_secret("PHABRICATOR_URL")
    61                                                   )
    62                                           
    63         1     770260.0 770260.0      4.1          diffs = phabricator_api.search_diffs(diff_id=diff_id)
    64         1          4.0      4.0      0.0          assert len(diffs) == 1, "No diff available for {}".format(diff_id)
    65         1          2.0      2.0      0.0          diff = diffs[0]
    66                                           
    67                                                   # Get the stack of patches
    68         1   14378246.0 14378246.0     76.9          base, patches = phabricator_api.load_patches_stack(hg, diff)
    69         1          4.0      4.0      0.0          assert len(patches) > 0, "No patches to apply"
    70                                           
    71                                                   # Load all the diffs details with commits messages
    72         1          2.0      2.0      0.0          diffs = phabricator_api.search_diffs(
    73         1     792468.0 792468.0      4.2              diff_phid=[p[0] for p in patches], attachments={"commits": True}
    74                                                   )
    75         1          3.0      3.0      0.0          commits = {
    76                                                       diff["phid"]: diff["attachments"]["commits"].get("commits", [])
    77         1          9.0      9.0      0.0              for diff in diffs
    78                                                   }
    79                                           
    80                                                   # First apply patches on local repo
    81         2          4.0      2.0      0.0          for diff_phid, patch in patches:
    82         1          1.0      1.0      0.0              commit = commits.get(diff_phid)
    83                                           
    84         1          1.0      1.0      0.0              message = ""
    85         1          1.0      1.0      0.0              if commit:
    86         1          9.0      9.0      0.0                  message += "{}\n".format(commit[0]["message"])
    87                                           
    88         1        196.0    196.0      0.0              logger.info(f"Applying {diff_phid}")
    89         1          6.0      6.0      0.0              hg.import_(
    90         1          9.0      9.0      0.0                  patches=io.BytesIO(patch.encode("utf-8")),
    91         1          1.0      1.0      0.0                  message=message,
    92         1    1995735.0 1995735.0     10.7                  user="bugbug",
    93                                                       )

Total time: 262.725 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: classify at line 95

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    95                                               @profile
    96                                               def classify(self, diff_id):
    97         1  214484165.0 214484165.0     81.6          self.update_commit_db()
    98                                           
    99         1     753935.0 753935.0      0.3          with hglib.open(self.repo_dir) as hg:
   100         1   18695383.0 18695383.0      7.1              self.apply_phab(hg, diff_id)
   101                                           
   102         1     109676.0 109676.0      0.0              patch_rev = hg.log(revrange="not public()")[0].node
   103                                           
   104                                                       # Analyze patch.
   105         1          7.0      7.0      0.0              commits = repository.download_commits(
   106         1   24489193.0 24489193.0      9.3                  self.repo_dir, rev_start=patch_rev.decode("utf-8"), ret=True, save=False
   107                                                       )
   108                                           
   109         1         17.0     17.0      0.0          probs, importance = self.model.classify(
   110         1    3656144.0 3656144.0      1.4              commits[-1], probabilities=True, importances=True
   111                                                   )
   112                                           
   113         1     471758.0 471758.0      0.2          feature_names = self.model.get_feature_names()
   114                                           
   115         1          2.0      2.0      0.0          features = []
   116         1          2.0      2.0      0.0          for i, (val, feature_index, is_positive) in enumerate(
   117         4         26.0      6.5      0.0              importance["importances"]
   118                                                   ):
   119         3          3.0      1.0      0.0              features.append(
   120                                                           [
   121         3          3.0      1.0      0.0                      i + 1,
   122         3          6.0      2.0      0.0                      feature_names[int(feature_index)],
   123         3         21.0      7.0      0.0                      f'({"+" if (is_positive) else "-"}{val})',
   124                                                           ]
   125                                                       )
   126                                           
   127         1       4203.0   4203.0      0.0          with open("probs.json", "w") as f:
   128         1        178.0    178.0      0.0              json.dump(probs[0].tolist(), f)
   129                                           
   130         1        129.0    129.0      0.0          with open("importance.html", "w") as f:
   131         1      59847.0  59847.0      0.0              f.write(importance["html"])

Clone ok, data ok
=================

Timer unit: 1e-06 s

Total time: 34.2974 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: update_commit_db at line 40

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    40                                               @profile
    41                                               def update_commit_db(self):
    42         1   12583395.0 12583395.0     36.7          repository.clone(self.repo_dir)
    43                                           
    44         1    1662951.0 1662951.0      4.8          db.download_version(repository.COMMITS_DB)
    45         1         60.0     60.0      0.0          if db.is_old_version(repository.COMMITS_DB) or not os.path.exists(
    46         1          9.0      9.0      0.0              repository.COMMITS_DB
    47                                                   ):
    48                                                       db.download(repository.COMMITS_DB, force=True, support_files_too=True)
    49                                           
    50    400943   19349343.0     48.3     56.4          for commit in repository.get_commits():
    51    400942     299068.0      0.7      0.9              pass
    52                                           
    53         1          4.0      4.0      0.0          rev_start = "children({})".format(commit["node"])
    54                                           
    55         1     402599.0 402599.0      1.2          repository.download_commits(self.repo_dir, rev_start)

Total time: 9.3412 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: apply_phab at line 57

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    57                                               @profile
    58                                               def apply_phab(self, hg, diff_id):
    59         1          3.0      3.0      0.0          phabricator_api = PhabricatorAPI(
    60         1     783401.0 783401.0      8.4              api_key=get_secret("PHABRICATOR_TOKEN"), url=get_secret("PHABRICATOR_URL")
    61                                                   )
    62                                           
    63         1     713519.0 713519.0      7.6          diffs = phabricator_api.search_diffs(diff_id=diff_id)
    64         1          4.0      4.0      0.0          assert len(diffs) == 1, "No diff available for {}".format(diff_id)
    65         1          1.0      1.0      0.0          diff = diffs[0]
    66                                           
    67                                                   # Get the stack of patches
    68         1    5420510.0 5420510.0     58.0          base, patches = phabricator_api.load_patches_stack(hg, diff)
    69         1          2.0      2.0      0.0          assert len(patches) > 0, "No patches to apply"
    70                                           
    71                                                   # Load all the diffs details with commits messages
    72         1          2.0      2.0      0.0          diffs = phabricator_api.search_diffs(
    73         1     719767.0 719767.0      7.7              diff_phid=[p[0] for p in patches], attachments={"commits": True}
    74                                                   )
    75         1          2.0      2.0      0.0          commits = {
    76                                                       diff["phid"]: diff["attachments"]["commits"].get("commits", [])
    77         1          3.0      3.0      0.0              for diff in diffs
    78                                                   }
    79                                           
    80                                                   # First apply patches on local repo
    81         2          5.0      2.5      0.0          for diff_phid, patch in patches:
    82         1          1.0      1.0      0.0              commit = commits.get(diff_phid)
    83                                           
    84         1          1.0      1.0      0.0              message = ""
    85         1          1.0      1.0      0.0              if commit:
    86         1          8.0      8.0      0.0                  message += "{}\n".format(commit[0]["message"])
    87                                           
    88         1        147.0    147.0      0.0              logger.info(f"Applying {diff_phid}")
    89         1          2.0      2.0      0.0              hg.import_(
    90         1          6.0      6.0      0.0                  patches=io.BytesIO(patch.encode("utf-8")),
    91         1          1.0      1.0      0.0                  message=message,
    92         1    1703812.0 1703812.0     18.2                  user="bugbug",
    93                                                       )

Total time: 70.1244 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/scripts/commit_classifier.py
Function: classify at line 95

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    95                                               @profile
    96                                               def classify(self, diff_id):
    97         1   34765407.0 34765407.0     49.6          self.update_commit_db()
    98                                           
    99         1     394179.0 394179.0      0.6          with hglib.open(self.repo_dir) as hg:
   100         1    9341290.0 9341290.0     13.3              self.apply_phab(hg, diff_id)
   101                                           
   102         1      77083.0  77083.0      0.1              patch_rev = hg.log(revrange="not public()")[0].node
   103                                           
   104                                                       # Analyze patch.
   105         1          7.0      7.0      0.0              commits = repository.download_commits(
   106         1   21335090.0 21335090.0     30.4                  self.repo_dir, rev_start=patch_rev.decode("utf-8"), ret=True, save=False
   107                                                       )
   108                                           
   109         1         16.0     16.0      0.0          probs, importance = self.model.classify(
   110         1    3739291.0 3739291.0      5.3              commits[-1], probabilities=True, importances=True
   111                                                   )
   112                                           
   113         1     422042.0 422042.0      0.6          feature_names = self.model.get_feature_names()
   114                                           
   115         1          3.0      3.0      0.0          features = []
   116         1          2.0      2.0      0.0          for i, (val, feature_index, is_positive) in enumerate(
   117         4         23.0      5.8      0.0              importance["importances"]
   118                                                   ):
   119         3          2.0      0.7      0.0              features.append(
   120                                                           [
   121         3          3.0      1.0      0.0                      i + 1,
   122         3          5.0      1.7      0.0                      feature_names[int(feature_index)],
   123         3         26.0      8.7      0.0                      f'({"+" if (is_positive) else "-"}{val})',
   124                                                           ]
   125                                                       )
   126                                           
   127         1       3964.0   3964.0      0.0          with open("probs.json", "w") as f:
   128         1        132.0    132.0      0.0              json.dump(probs[0].tolist(), f)
   129                                           
   130         1         48.0     48.0      0.0          with open("importance.html", "w") as f:
   131         1      45827.0  45827.0      0.1              f.write(importance["html"])
```

**Comment by marco-c** [comment]
Some of those steps will only be done once at startup (e.g. clone). Could you get the timing also of a second run?

**Comment by Lothiraldan** [comment]
Here are the extracted timings for the raw timings pasted in top.

# Run 1

The repository was not there nor the DB.

Total time: 28 minutes 30 seconds

* Repository clone: 27 minutes 40 seconds
* Iterating on all commit: 16.96 seconds.
* Download all the commits before applying the patch: 30.99 seconds.

Then the run failed because I didn't had a phabricator token.

# Run 2

The repository was cloned but not the DBs.

Total time: 3 minutes 34 seconds

* Repository checking + stripping: 14.49 seconds.
* Download the data version: 3.2 seconds.
* Download the data: 32.30 seconds.
* Iterating on all commits: 21 seconds.
* Download all the commits before applying the patch: 142.50 seconds.
* Applying the phab patch: 18.70s.
  * Getting the patch from phabricator: 14.37s.
  * Importing the patches: 2s.
* Downloading the commits after the patch has been applied: 24.49s
* Actual classification: 3.65s.

# Run 3

The repository was cloned and the DBs were downloaded and up-to-date.

Total time: 34.30s.

* Repository checking + stripping: 12.58 seconds.
* Download the data version: 1.66 seconds.
* Download the data: DB up-to-date.
* Iterating on all commits: 19.35 seconds.
* Download all the commits before applying the patch: 0.4 seconds.
* Applying the phab patch: 9.34s.
  * Getting the patch from phabricator: 5.42s.
  * Importing the patches: 1.70s.
* Downloading the commits after the patch has been applied: 21.33s
* Actual classification: 3.74s.

Here are a table of timings:

|                                                          	| Run 1                 	| Run 2          	| Run 3         	|
|----------------------------------------------------------	|-----------------------	|----------------	|---------------	|
| Repository clone                                         	| 27 minutes 40 seconds 	|                	|               	|
| Repository check + stripping                             	|                       	| 14.49 seconds  	| 12.58 seconds 	|
| Download the data version                                	| 1.57 seconds          	| 3.2 seconds    	| 1.66 seconds  	|
| Download the data                                        	|                       	| 32.30 seconds  	| 1.66 seconds  	|
| Iterating on all commits                                 	| 16.96 seconds         	| 21 seconds     	| 19.35 seconds 	|
| Download all the commits before applying the patch       	| 30.99 seconds         	| 142.50 seconds 	| 0.4 seconds   	|
| Applying the phab patch                                  	|                       	| 18.70s         	| 9.34s         	|
| # Getting the patch from phabricator                     	|                       	| 14.37s         	| 5.42s         	|
| # Importing the patches                                  	|                       	| 2s             	| 1.70s         	|
| Downloading the commits after the patch has been applied 	|                       	| 24.49s         	| 21.33s        	|
| Actual classification                                    	|                       	| 3.65s          	| 3.74s         	|

**Comment by Lothiraldan** [comment]
Here is the timings from `bugbug.repository.download_commits`, bear in mind that it is called two times, one before applying the patch and one after:

Timings:

Total time: 41.10s per call.

* Getting the first commit node: 1.49s per call.
* Getting the log of commits: 6.12s per call.
* Downloading the component mapping: 2.90s per call.
* Computing the experiences: 28.87s per call.
* Transformating the commits: 1.31s per call.

Here is the raw data:

```
Timer unit: 1e-06 s

Total time: 82.2131 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/bugbug/repository.py
Function: download_commits at line 672

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   672                                           @profile
   673                                           def download_commits(repo_dir, rev_start=0, ret=False, save=True):
   674         2     915472.0 457736.0      1.1      hg = hglib.open(repo_dir)
   675                                           
   676         2     381175.0 190587.5      0.5      revs = get_revs(hg, rev_start)
   677         2         12.0      6.0      0.0      if len(revs) == 0:
   678                                                   print("No commits to analyze")
   679                                                   return []
   680                                           
   681         2    2989620.0 1494810.0      3.6      first_pushdate = hg_log(hg, [b"0"])[0].pushdate
   682                                           
   683         2     120654.0  60327.0      0.1      hg.close()
   684                                           
   685         2        154.0     77.0      0.0      processes = multiprocessing.cpu_count()
   686                                           
   687         2         89.0     44.5      0.0      print(f"Mining {len(revs)} commits using {processes} processes...")
   688                                           
   689         2         10.0      5.0      0.0      CHUNK_SIZE = 256
   690         2         46.0     23.0      0.0      revs_groups = [revs[i : (i + CHUNK_SIZE)] for i in range(0, len(revs), CHUNK_SIZE)]
   691                                           
   692         2         24.0     12.0      0.0      with concurrent.futures.ProcessPoolExecutor(
   693         2       2751.0   1375.5      0.0          initializer=_init, initargs=(repo_dir,)
   694         2          5.0      2.5      0.0      ) as executor:
   695         2     280236.0 140118.0      0.3          commits = executor.map(_hg_log, revs_groups, chunksize=20)
   696         2      25639.0  12819.5      0.0          commits = tqdm(commits, total=len(revs_groups))
   697         2   12268623.0 6134311.5     14.9          commits = list(itertools.chain.from_iterable(commits))
   698                                           
   699         2         81.0     40.5      0.0      print("Downloading file->component mapping...")
   700                                           
   701         2    5806262.0 2903131.0      7.1      download_component_mapping()
   702                                           
   703         2       6208.0   3104.0      0.0      commits_to_ignore = get_commits_to_ignore(repo_dir, commits)
   704         2         46.0     23.0      0.0      print(f"{len(commits_to_ignore)} commits to ignore")
   705                                           
   706         2   57751710.0 28875855.0     70.2      calculate_experiences(commits, commits_to_ignore, first_pushdate, save)
   707                                           
   708                                               # Exclude commits to ignore.
   709         2        144.0     72.0      0.0      commits = [commit for commit in commits if commit not in commits_to_ignore]
   710                                           
   711         2          5.0      2.5      0.0      commits_num = len(commits)
   712                                           
   713         2         79.0     39.5      0.0      print(f"Mining {commits_num} commits using {processes} processes...")
   714                                           
   715                                               global rs_parsepatch
   716         2      19399.0   9699.5      0.0      import rs_parsepatch
   717                                           
   718         2          7.0      3.5      0.0      with concurrent.futures.ProcessPoolExecutor(
   719         2       2942.0   1471.0      0.0          initializer=_init, initargs=(repo_dir,)
   720         2         19.0      9.5      0.0      ) as executor:
   721         2     190258.0  95129.0      0.2          commits = executor.map(_transform, commits, chunksize=64)
   722         2       9058.0   4529.0      0.0          commits = tqdm(commits, total=commits_num)
   723                                           
   724         2          7.0      3.5      0.0          if ret:
   725         1    1310102.0 1310102.0      1.6              commits = list(commits)
   726                                           
   727         2          3.0      1.5      0.0          if save:
   728         1       5343.0   5343.0      0.0              db.append(COMMITS_DB, commits)
   729                                           
   730         2        146.0     73.0      0.0          if ret:
   731         1     126814.0 126814.0      0.2              return commits
```

```
Timer unit: 1e-06 s

Total time: 82.2131 s
File: /home/lothiraldan/project/mozilla-automl/bugbug/bugbug/repository.py
Function: download_commits at line 672

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   672                                           @profile
   673                                           def download_commits(repo_dir, rev_start=0, ret=False, save=True):
   674         2     915472.0 457736.0      1.1      hg = hglib.open(repo_dir)
   675                                           
   676         2     381175.0 190587.5      0.5      revs = get_revs(hg, rev_start)
   677         2         12.0      6.0      0.0      if len(revs) == 0:
   678                                                   print("No commits to analyze")
   679                                                   return []
   680                                           
   681         2    2989620.0 1494810.0      3.6      first_pushdate = hg_log(hg, [b"0"])[0].pushdate
   682                                           
   683         2     120654.0  60327.0      0.1      hg.close()
   684                                           
   685         2        154.0     77.0      0.0      processes = multiprocessing.cpu_count()
   686                                           
   687         2         89.0     44.5      0.0      print(f"Mining {len(revs)} commits using {processes} processes...")
   688                                           
   689         2         10.0      5.0      0.0      CHUNK_SIZE = 256
   690         2         46.0     23.0      0.0      revs_groups = [revs[i : (i + CHUNK_SIZE)] for i in range(0, len(revs), CHUNK_SIZE)]
   691                                           
   692         2         24.0     12.0      0.0      with concurrent.futures.ProcessPoolExecutor(
   693         2       2751.0   1375.5      0.0          initializer=_init, initargs=(repo_dir,)
   694         2          5.0      2.5      0.0      ) as executor:
   695         2     280236.0 140118.0      0.3          commits = executor.map(_hg_log, revs_groups, chunksize=20)
   696         2      25639.0  12819.5      0.0          commits = tqdm(commits, total=len(revs_groups))
   697         2   12268623.0 6134311.5     14.9          commits = list(itertools.chain.from_iterable(commits))
   698                                           
   699         2         81.0     40.5      0.0      print("Downloading file->component mapping...")
   700                                           
   701         2    5806262.0 2903131.0      7.1      download_component_mapping()
   702                                           
   703         2       6208.0   3104.0      0.0      commits_to_ignore = get_commits_to_ignore(repo_dir, commits)
   704         2         46.0     23.0      0.0      print(f"{len(commits_to_ignore)} commits to ignore")
   705                                           
   706         2   57751710.0 28875855.0     70.2      calculate_experiences(commits, commits_to_ignore, first_pushdate, save)
   707                                           
   708                                               # Exclude commits to ignore.
   709         2        144.0     72.0      0.0      commits = [commit for commit in commits if commit not in commits_to_ignore]
   710                                           
   711         2          5.0      2.5      0.0      commits_num = len(commits)
   712                                           
   713         2         79.0     39.5      0.0      print(f"Mining {commits_num} commits using {processes} processes...")
   714                                           
   715                                               global rs_parsepatch
   716         2      19399.0   9699.5      0.0      import rs_parsepatch
   717                                           
   718         2          7.0      3.5      0.0      with concurrent.futures.ProcessPoolExecutor(
   719         2       2942.0   1471.0      0.0          initializer=_init, initargs=(repo_dir,)
   720         2         19.0      9.5      0.0      ) as executor:
   721         2     190258.0  95129.0      0.2          commits = executor.map(_transform, commits, chunksize=64)
   722         2       9058.0   4529.0      0.0          commits = tqdm(commits, total=commits_num)
   723                                           
   724         2          7.0      3.5      0.0          if ret:
   725         1    1310102.0 1310102.0      1.6              commits = list(commits)
   726                                           
   727         2          3.0      1.5      0.0          if save:
   728         1       5343.0   5343.0      0.0              db.append(COMMITS_DB, commits)
   729                                           
   730         2        146.0     73.0      0.0          if ret:
   731         1     126814.0 126814.0      0.2              return commits
```

**Comment by Lothiraldan** [comment]
`bugbug.repository.calculate_experiences` time seems mostly taken by loading the experience pickle file (66%) and dumping it (32.9%).

**Comment by marco-c** [comment]
>  Getting the first commit node: 1.49s per call.
    Getting the log of commits: 6.12s per call.
    Downloading the component mapping: 2.90s per call.
    Computing the experiences: 28.87s per call.
    Transformating the commits: 1.31s per call.

We could do a few of these steps only periodically (e.g. once per day) given that the data won't change much between two subsequent runs.
`Getting the log of commits` can be sped up by avoiding using multiple processes (we pay a big startup cost for analyzing only a few patches in this case).
`Downloading the component mapping` can definitely be done only periodically.
`Computing the experiences` the load of the pickle file can definitely be done only periodically. The dump is already avoided in this case (as save is False).
`Transformating the commits` like `Getting the log of commits`.

**Comment by marco-c** [comment]
This should now be done, modulo possible bugs to fix.

**Comment by marco-c** [comment]
(and improvements to make it faster)
