### ISSUE TITLE
Perform text cleanup

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#9]
We are not cleaning up the text from title or comments at all, we should:
- [x] replace crash stats references (bp-XXXX, example in https://bugzilla.mozilla.org/show_bug.cgi?id=1376831#c0) with one or more tokens (e.g. "\_\_\_CRASH_STATS_LINK\_\_\_")
- [x] replace file references with one or more tokens (e.g. "\_\_\_FILE_REFERENCE\_\_\_") - #36.
- [x] replace URLs with one or more tokens (e.g. "\_\_\_URL\_\_\_") - #33.
- [x] maybe remove referred text in comments (starting with ">") - #52.
- [x] replace hexadecimal numbers with one or more tokens (e.g. "\_\_HEX_NUMBER\_\_") - #56.
- [x] replace DLL names with one or more tokens (e.g. "\_\_DLL_NAME\_\_"). - #65.
    - [ ] Possibly only the third-party DLLs and not the Firefox ones (e.g. XUL.dll).

For URLs, we should probably have different tokens according to the type of URL (e.g. if it's a hg.mozilla.org, or searchfox.org or dxr.mozilla.org, then the meaning of the URL might be different).

**Comment by ayush1999** [comment]
@marco-c We could add a check for removing the text inside `<>`, which are generally emails (in the commits.json file), since they aren't of any use. This shouldn't be hard to do, a simple filter and lambda function should be enough to do this. Need your go-ahead on this.

**Comment by marco-c** [comment]
I'd focus mostly on the bug data (title and comments), as that where most of the cleanup should be done first.
The emails in commits.json should be pretty rare.

**Comment by ayush1999** [comment]
@marco-c What kind of checks should be done for URLs that aren't in the regular form? (Such as hg.mozilla.org, or searchfox.org, as you mentioned?) (URLs that haven't been written starting with `http`)

**Comment by marco-c** [comment]
I meant that for those URLs (http{s}://hg.mozilla.org, http{s}://searchfox) we might want to try to assing a separate token (not URL, but something like CODE_REFERENCE_URL).

**Comment by ayush1999** [comment]
@marco-c How can stack traces be identified? (I'm guessing they might be enclosed in some special character?)

**Comment by marco-c** [comment]
Here are two examples https://bugzilla.mozilla.org/show_bug.cgi?id=1376831#c0 and https://bugzilla.mozilla.org/show_bug.cgi?id=1515375#c0, but it isn't so easy, maybe it's better not to do it or to try it after we're done with the others.

**Comment by ayush1999** [comment]
@marco-c For replacing the crash stats, would a check for all words starting with `bp-` suffice?

**Comment by marco-c** [comment]
I think it'd be better to have a more precise regex, we can probably find it somewhere as Bugzilla is using it to detect the links (indeed if you open one of those bugs, you can see that bp-XXX is a link).

**Comment by ayush1999** [comment]
Oh, also, could you point me to a bug example that uses hex numbers in the text?

**Comment by marco-c** [comment]
Sure, here's an example: https://bugzilla.mozilla.org/show_bug.cgi?id=1489041.

**Comment by ayush1999** [comment]
If I'm not wrong, the hex numbers in the issue are already in `>`, so they get eliminated by #52 . Do we still need a check for substituting these numbers? (Maybe because #52 hasn't been merged yet?)

**Comment by marco-c** [comment]
Only some are in `>`, but not all. For example see the title of the bug (it contains scdetour.dll@0x2dd77), or the first comment.

**Comment by ayush1999** [comment]
@marco-c Regarding cleanup for crash references, should I replace only the bp-XXXX part or the entire crash stat? Plus the bugs.json data doesn't have any indication to check if a certain text is a hyperlink or not.

**Comment by marco-c** [comment]
> @marco-c Regarding cleanup for crash references, should I replace only the bp-XXXX part or the entire crash stat?

I'd say only the bp-XXXX part.

> Plus the bugs.json data doesn't have any indication to check if a certain text is a hyperlink or not.

What do you mean?

**Comment by ayush1999** [comment]
You mentioned in an earlier comment that we'd need to have a regex that checks for all `bp-XXX` words that are also links. Right?

**Comment by marco-c** [comment]
> You mentioned in an earlier comment that we'd need to have a regex that checks for all bp-XXX words that are also links. Right?

Sorry, I wasn't clear enough. We need to replace the bp-XXX words only. I only meant that there must be a regex somewhere already, as Bugzilla itself is detecting the bp-XXX words and turning them into links (in its interface, not in its DB, that's why our bugs.json only contains the bp-XXX words and not the link).

**Comment by ayush1999** [comment]
Oh, I see. I guess I misunderstood. I just skimmed through the bugzilla repo, but was unable to find the matching regex. A regex such as `bp-\w+-\w+-\w+-\w+-\w+` should work, right?

**Comment by marco-c** [comment]
Here it is, found it in the Socorro repo: https://github.com/mozilla-services/socorro/blob/fc00cb6a9321b33c2971a2c14c7d916638e33a14/socorro/lib/ooid.py#L68-L88.

**Comment by ayush1999** [comment]
Ah, thanks a lot.

**Comment by marco-c** [comment]
The text on Bugzilla comments is free text, so there isn't a rule that specifies stack traces to always start with `>`. Some people use `>` before stack traces, some people don't. Same with code snippets and so on.

Anyway, I guess cleaning up stack traces is not so easy, so I'd say we can ignore it for now.
